### ISSUE TITLE
should recognize --testcase option

### ISSUE THREAD

**Issue by lhm** [turn-project/turn#11]
the standard test/unit runner has the option to run only specific testcases with the --testcase (or -t) PATTERN option, which is currently not recognized by turn:

```
$ turn -t /JsonApi/ functional/locations_controller_test.rb 
/usr/bin/turn: invalid option -- t
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/getoptlong.rb:403:in `set_error': invalid option -- t (GetoptLong::InvalidOption)
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/getoptlong.rb:580:in `get_option'
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/getoptlong.rb:611:in `each'
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/getoptlong.rb:610:in `loop'
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/getoptlong.rb:610:in `each'
from /Library/Ruby/Gems/1.8/gems/turn-0.7.0/lib/turn/command.rb:62
from /Library/Ruby/Gems/1.8/gems/turn-0.7.0/bin/turn:3:in `load'
from /Library/Ruby/Gems/1.8/gems/turn-0.7.0/bin/turn:3
from /usr/bin/turn:19:in `load'
from /usr/bin/turn:19
```

**Comment by trans** [comment]
Feature has been added v0.8.2.
