### ISSUE TITLE
turn barfs on rbx *.rbc files

### ISSUE THREAD

**Issue by tmm1** [turn-project/turn#24]
```
rubies/ruby-1.8.7-p330/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require': no such file to load -- /Users/test/code/beefcake/test/buffer_decode_test.rbc (LoadError)
  from rubies/ruby-1.8.7-p330/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:29:in `require'
  from gems/ruby-1.8.7-p330/gems/turn-0.8.1/lib/turn/runners/testrunner.rb:28:in `initialize'
  from gems/ruby-1.8.7-p330/gems/turn-0.8.1/lib/turn/runners/testrunner.rb:28:in `each'
  from gems/ruby-1.8.7-p330/gems/turn-0.8.1/lib/turn/runners/testrunner.rb:28:in `initialize'
  from gems/ruby-1.8.7-p330/gems/turn-0.8.1/lib/turn/controller.rb:137:in `new'
  from gems/ruby-1.8.7-p330/gems/turn-0.8.1/lib/turn/controller.rb:137:in `start'
  from gems/ruby-1.8.7-p330/gems/turn-0.8.1/lib/turn/command.rb:199:in `main'
  from gems/ruby-1.8.7-p330/gems/turn-0.8.1/lib/turn/command.rb:37:in `main'
  from gems/ruby-1.8.7-p330/gems/turn-0.8.1/bin/turn:3
  from gems/ruby-1.8.7-p330/bin/turn:19:in `load'
  from gems/ruby-1.8.7-p330/bin/turn:19
```

**Comment by tmm1** [comment]
should be fixed by

```
diff --git a/lib/turn/controller.rb b/lib/turn/controller.rb
index cf35289..edbbf91 100644
--- a/lib/turn/controller.rb
+++ b/lib/turn/controller.rb
@@ -60,7 +60,7 @@ module Turn
     #
     def initialize_defaults
       @loadpath ||= ['lib']
-      @tests    ||= "test/**/{test,}*{,test}"
+      @tests    ||= "test/**/{test,}*{,test}*rb"
       @exclude  ||= []
       @requires ||= []
       @live     ||= false
```

**Comment by trans** [comment]
Good idea. I added `.rb`:

```
@tests    ||= "test/**/{test,}*{,test}*.rb"
```
