### ISSUE TITLE
Command line utility doesn't work?

### ISSUE THREAD

**Issue by defunkt** [turn-project/turn#3]
```
$ turn -h
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- facets/progressbar (LoadError)
  from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
  from /Users/chris/.gems/gems/turn-0.6.2/lib/turn/reporters/progress_reporter.rb:2
  from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
  from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
  from /Users/chris/.gems/gems/turn-0.6.2/lib/turn/controller.rb:10
  from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
  from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
  from /Users/chris/.gems/gems/turn-0.6.2/lib/turn/command.rb:25
  from /Users/chris/.gems/gems/turn-0.6.2/bin/turn:3:in `load'
  from /Users/chris/.gems/gems/turn-0.6.2/bin/turn:3
  from /Users/chris/.gems/bin/turn:19:in `load'
  from /Users/chris/.gems/bin/turn:19
```

I have facets installed:

```
$ gem list facets

*** LOCAL GEMS ***

facets (2.8.0)
```

**Comment by TwP** [comment]
The progressbar class was moved out of facets and into the ansi gem. Thanks for letting me know. New release (v0.6.3) has been pushed out to rubyforge and gemcutter.

Blessings,
TwP
